const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
let currentUser = null, tracks = [], trackIndex = 0;
const audio = $('#audio'), storyAudio = $('#storyAudio');
async function api(url, options = {}) { const res = await fetch(url, options); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.error || 'تعذّر تنفيذ الطلب.'); return data; }
function escapeHtml(value = '') { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function go(id) { $$('.screen').forEach(s => s.classList.remove('active')); const el = $('#' + id); if (el) el.classList.add('active'); window.scrollTo({ top: 0, behavior: 'smooth' }); if (id === 'story8' && audio.src) { audio.pause(); audio.currentTime = 0; storyAudio.play().catch(() => {}); } if (['playlist', 'photos', 'videos'].includes(id)) loadMedia(); if (id === 'admin') loadAdminMedia(); }
function particles() { const p = $('#particles'), petals = $('#petals'); for (let i = 0; i < 30; i++) { const e = document.createElement('i'); e.className = 'particle'; e.style.left = Math.random() * 100 + '%'; e.style.animationDelay = -Math.random() * 8 + 's'; e.style.animationDuration = 6 + Math.random() * 7 + 's'; p.appendChild(e); } for (let i = 0; i < 10; i++) { const e = document.createElement('i'); e.className = 'petal'; e.textContent = '🌹'; e.style.left = Math.random() * 100 + '%'; e.style.animationDelay = -Math.random() * 9 + 's'; e.style.animationDuration = 8 + Math.random() * 5 + 's'; petals.appendChild(e); } }
function setMusicState(on) { $('#musicToggle').textContent = on ? '🔊 الموسيقى شغالة' : '🔇 الموسيقى متوقفة'; }
function startMusic() { if (audio.src) { audio.volume = .72; audio.play().then(() => setMusicState(true)).catch(() => setMusicState(false)); } }
function playTrack(i) { trackIndex = i; const t = tracks[i]; if (!t) return; $('#trackTitle').textContent = t.title; $('#trackArtist').textContent = t.artist || 'مضافة من الموقع'; audio.src = t.url; audio.play().catch(() => {}); }
function deleteButton(id) { return `<button class="delete-media" data-delete-media="${id}">حذف</button>`; }
function renderTracks() { $('#tracks').innerHTML = tracks.length ? tracks.map((t, i) => `<div class="track"><div><b>${escapeHtml(t.title)}</b><small>${escapeHtml(t.artist || 'مضافة من الموقع')}</small></div><button data-track="${i}">▶</button>${deleteButton(t.id)}</div>`).join('') : '<p class="muted">لا توجد موسيقى مضافة بعد.</p>'; $$('[data-track]').forEach(b => b.onclick = () => playTrack(Number(b.dataset.track))); }
function renderPhotos(items) { $('#photoGrid').innerHTML = items.length ? items.map(m => `<div class="photo"><img src="${m.url}" alt="${escapeHtml(m.title)}"><span>${escapeHtml(m.title)}</span>${deleteButton(m.id)}</div>`).join('') : '<p class="muted">لا توجد صور مضافة بعد.</p>'; }
function renderVideos(items) { $('#videoList').innerHTML = items.length ? items.map(m => `<div class="video-card"><video controls playsinline preload="metadata" src="${m.url}"></video><p>${escapeHtml(m.title)} ${deleteButton(m.id)}</p></div>`).join('') : '<p class="muted">لا توجد فيديوهات مضافة بعد.</p>'; }
function bindDeleteButtons() { $$('[data-delete-media]').forEach(button => button.onclick = async () => { if (!confirm('حذف هذا الملف نهائيًا؟')) return; try { await api(`/api/media/${button.dataset.deleteMedia}`, { method: 'DELETE' }); await loadMedia(); } catch (err) { alert(err.message); } }); }
async function loadMedia() { try { const { media } = await api('/api/media'); tracks = media.filter(m => m.type === 'audio'); renderTracks(); renderPhotos(media.filter(m => m.type === 'image')); renderVideos(media.filter(m => m.type === 'video')); bindDeleteButtons(); if (tracks.length && !audio.src.includes('/uploads/')) playTrack(0); } catch (err) { console.error(err); } }
async function uploadMedia(input, type) { const files = [...input.files]; if (!files.length) return; const status = $('#uploadStatus'); status.textContent = `جارٍ رفع ${files.length} ملف…`; const form = new FormData(); files.forEach(file => form.append('files', file)); form.append('type', type); try { const result = await api('/api/media', { method: 'POST', body: form }); status.textContent = `تم حفظ ${result.media.length} من ${files.length} ملف في قاعدة البيانات.`; input.value = ''; await loadMedia(); } catch (err) { status.textContent = err.message; } }
function ensureAdmin() { let section = $('#admin'); if (currentUser?.role === 'admin' && !section) { section = document.createElement('section'); section.id = 'admin'; section.className = 'screen app-section'; section.innerHTML = `<button class="back" data-go="home">← رجوع</button><div class="section-title"><span>⚙️</span><div><p>الإدارة</p><h2>إدارة الملفات</h2></div></div><div id="adminMedia" class="list"></div>`; $('main').appendChild(section); section.querySelector('[data-go]').onclick = () => go('home'); const adminButton = document.createElement('button'); adminButton.className = 'secret-card'; adminButton.innerHTML = '<span>⚙️</span><div><b>لوحة الإدارة</b><small>إظهار أو إخفاء وحذف الملفات</small></div><i>←</i>'; adminButton.onclick = () => go('admin'); $('.secret-card').after(adminButton); } }
async function loadAdminMedia() { try { const { media } = await api('/api/admin/media'); $('#adminMedia').innerHTML = media.length ? media.map(m => `<div class="track admin-row"><div><b>${escapeHtml(m.title)}</b><small>${m.type} · ${escapeHtml(m.owner_name)} · ${m.is_visible ? 'ظاهر' : 'مخفي'}</small></div><button class="admin-action" data-toggle="${m.id}" data-visible="${m.is_visible}">${m.is_visible ? 'إخفاء' : 'إظهار'}</button><button class="admin-action delete" data-delete="${m.id}">حذف</button></div>`).join('') : '<p class="muted">لا توجد ملفات.</p>'; $$('[data-toggle]').forEach(b => b.onclick = async () => { await api(`/api/admin/media/${b.dataset.toggle}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_visible: b.dataset.visible !== 'true' }) }); loadAdminMedia(); }); $$('[data-delete]').forEach(b => b.onclick = async () => { if (confirm('حذف الملف نهائيًا؟')) { await api(`/api/media/${b.dataset.delete}`, { method: 'DELETE' }); loadAdminMedia(); } }); } catch (err) { $('#adminMedia').textContent = err.message; } }
async function login() { const button = $('#loginBtn'); button.disabled = true; try { const { user } = await api('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: $('#username').value, password: $('#password').value }) }); currentUser = user; $('#login').classList.add('hidden'); ensureAdmin(); go('welcome'); startMusic(); loadMedia(); } catch (err) { alert(err.message); } finally { button.disabled = false; } }
async function restoreSession() { const { user } = await api('/api/auth/me'); if (user) { currentUser = user; $('#login').classList.add('hidden'); ensureAdmin(); loadMedia(); } }
$$('[data-story]').forEach(b => b.addEventListener('click', () => go(b.dataset.story === 'home' ? 'home' : b.dataset.story))); $$('[data-go]').forEach(b => b.addEventListener('click', () => go(b.dataset.go)));
$('#loginBtn').addEventListener('click', login); $('#password').addEventListener('keydown', e => { if (e.key === 'Enter') login(); }); $('#logout').addEventListener('click', async () => { await api('/api/auth/logout', { method: 'POST' }); audio.pause(); currentUser = null; location.reload(); });
$('#musicToggle').addEventListener('click', () => audio.paused ? audio.play().then(() => setMusicState(true)).catch(() => {}) : (audio.pause(), setMusicState(false))); $('#finalReveal').addEventListener('click', () => go('story12')); $$('.choice').forEach(b => b.addEventListener('click', () => { $('#answerText').textContent = b.dataset.answer === 'sure' ? 'كنت حاسس إنك هتختاري دي 😂… بس برضه مش هقولك أكتر.' : 'أهو ده الاختيار اللي كنت مستنيه 😌… كمّلي، يمكن تلاقي الإجابة لوحدك.'; setTimeout(() => go('story11'), 1100); })); $('#reveal').addEventListener('click', () => $('#secretMessage').classList.add('show'));
['audioUpload', 'photoUpload', 'videoUpload'].forEach(id => { $("#" + id).multiple = true; });
$('#audioUpload').addEventListener('change', e => uploadMedia(e.target, 'audio')); $('#photoUpload').addEventListener('change', e => uploadMedia(e.target, 'image')); $('#videoUpload').addEventListener('change', e => uploadMedia(e.target, 'video')); $('#play').addEventListener('click', () => audio.paused ? audio.play().catch(() => {}) : audio.pause()); $('#prev').addEventListener('click', () => playTrack((trackIndex - 1 + tracks.length) % tracks.length)); $('#next').addEventListener('click', () => playTrack((trackIndex + 1) % tracks.length)); particles(); setMusicState(false); restoreSession().catch(() => {});
